export const MENUS = [
    "Bize Ulaşın",
    "Telefon Ayarları",
    "Çağrı Hizmetleri",
    "Çağrı Yönlendirme",
    "Sim Kart Değişikliği",
    "Kayıp Çalıntı Kapama",
    "Numara Değişikliği",
    "Hat Bilgileri",
    "Yapacaklarım",
    "Fatura Detayları",
    "Abonelik İptal İşlemleri",
    "Özet Kullanım Raporu",
    "Güncel Kullanım Detayı",
    "MMS Mesajlarım",
    "Mevcut Paketlerim",
    "Abonelik Form ve Sözleşmeleri",
    "Tüketici Şikayetleri",
    "Fatura Gönderim Ayarları",
    "Canlı Destek",
    "Görüntülü Görüşme",
    "İşlem Kayıtlarım",
    "Kredi Kartı ile Paket Yükleme",
    "Sana Özel Avantajlı Faturalı Tarifeler",
    "Otomatik TL Yükleme Talimatı",
    "Talimatlarım",
    "Size Özel Kampanyalar",
    "11855 Rehber Servisi",
    "Yükleme Kartı ile Netten Yükle",
    "Kısa Numara İşlemleri",
    "Kullanıcı Hat Bilgileri",
    "MMS Paketi",
    "İnternet Paketleri",
    "SMS Paketleri",
    "Hediye İnternet",
    "İletişim Bilgileri Değişikliği",
    "Dil Değişikliği",
    "Sim Kart Talebi",
    "Ek Hat Talebi",
    "Dönüşen Tarifeler",
    "Kalan Bakiye",
    "Kurumsal Web Raporlama",
    "Referans Sistemi",
    "Bilgilerim",
    "Esnek IVR",
    "Konuşkan Paketler",
    "TL Kullanım Bilgilerim",
    "Tüm Servisler",
    "Servislerim",
    "Centrex İşlemlerim",
    "İzin Ayarları",
    "Yurtdışı Paketleri",
    "KK ile Lira Yükleme",
    "Paket Satın Alma",
    "Fatura Servisleri",
    "Bilgilendirme Mesajları",
    "Fatura Üst Sınır İşlemleri",
    "Yurt Dışı İnternet Kullanım Sınırı",
    "Hat Kullanıcısı Değişikliği",
    "Konuşma Paketleri",
    "Tarife ve Taahhüt İşlemleri",
    "Paket Kullanımlarım",
    "eSIM'e Geçiş",
    "Kullanım Detaylarım",
    "Fatura Bilgileri",
    "M2M Cihaz TAC Kodu Tanımlama",
    "M2M Hat Bazında Cihaz Eşleştirme",
    "Netflix",
    "Güncel Fatura ve Kullanım Bilgileri",
    "Sol Menü İsimleri",
    "Dijital Ürün ve Servis Satın Al",
    "Aktif Dijital Ürün ve Servislerim",
    "Ek Paket Al",
    "Faturalarım"
];
